<x-layouts.porto title="Earnings By Clients Per Month" 
header="Earnings By Clients Per Month" 
username={{$username}} 
profile_image={{$profile_image}} 
unread_notifications_number={{$unread_notifications_number}} 
:unread_notifications="$unread_notifications">
   
    @if(isset($earningsofclients))
      @php      
      $earningsperclients = collect($earningsofclients)->sortBy('sum')->reverse()->toArray();
      @endphp    

      @foreach($earningsperclients as $earningsperclient)
      <h3>Total earnings generated by <strong>{{$earningsperclient['name']}}</strong> per month: <strong><font color="green">{{$earningsperclient['sum']}} USD</font>,<font color="blue"> {{round(($earningsperclient['sum']/$totalsum)*100)}} %</font></strong></h3><br>
      @endforeach
      <!-- Flot: Pie -->
			<div class="chart chart-md" id="flotPie"></div>
			<script type="text/javascript">
        var flotPieData = [
          @foreach($earningsofclients as $index => $client)
          {
              label: "{{ $client['name'] }}",
              data: [
                  [1, {{ $client['sum'] }}]
              ],
              color: getRandomColor()
          }@if(!$loop->last),@endif
          @endforeach
        ];

        function getRandomColor() {
        // Generates a random hex color
        return '#' + Math.floor(Math.random()*16777215).toString(16);
    }
</script>
    @else
    <h3>Total earnings per month: <strong>0 USD</strong></h3>
    @endif

    @foreach($clients as $client)
      @php
        $sum = $client->tasks()->onlyTrashed()->sum('budget');        
      @endphp
      @if($sum > 0)      
        <strong><h1>{{$client->name}}</h1></strong><br>
        <table class="table">
<thead>
<tr>  
  <th scope="col">Task</th>
  <th scope="col">Word Count</th>
  <th scope="col">Budget, $USD</th>
  <th scope="col">Performance</th>
  <th scope="col">Due date</th>
  <th scope="col">Author</th>
  <th scope="col">Completion date</th>         
</tr>
</thead>
<tbody>
    @foreach($client->tasks()->onlyTrashed()->get() as $task)                
<tr>
  <td>{{ $task->task }}</td>
  <td>{{ $task->wordcount }}</td> 
  <td>{{ $task->budget }}</td>  
  <td>{!! $task->performance !!}</td> 
  <td>{{ $task->duedate }}</td> 
  <td>{{ $task->author }}</td>
  <td>{{ $task->deleted_at }}</td> 
</tr>
    @endforeach
</tbody>
</table>
<strong><h3>Total earnings generated by {{$client->name}} per month: {{$sum}} USD</h3></strong><br>
@endif    
@endforeach
</x-layouts.porto>