<x-layouts.porto title="Earnings by Clients per Month" header="Earnings by Clients per Month">

    @foreach($clients as $client)
      @php
        $sum = $client->tasks()->onlyTrashed()->sum('budget');        
      @endphp
        @if($sum > 0)
          @php
            $earningsofclients[] = array('name' => $client->name,'sum' => $sum);      
          @endphp
        @endif
    @endforeach

    @if(isset($earningsofclients))
      @php      
      $earningsperclients = collect($earningsofclients)->sortBy('sum')->reverse()->toArray();
      @endphp    

      @foreach($earningsperclients as $earningsperclient)
      <h3>Total earnings generated by <strong>{{$earningsperclient['name']}}</strong> per month: <strong>{{$earningsperclient['sum']}} USD</strong></h3><br>
      @endforeach
    @endif

    @foreach($clients as $client)
      @php
        $sum = $client->tasks()->onlyTrashed()->sum('budget');        
      @endphp
      @if($sum > 0)      
        <strong><h1>{{$client->name}}</h1></strong><br>
        <table class="table">
<thead>
<tr>  
  <th scope="col">Task</th>
  <th scope="col">Budget, $USD</th>
  <th scope="col">Performance</th>
  <th scope="col">Due date</th>
  <th scope="col">Author</th>
  <th scope="col">Completion date</th>         
</tr>
</thead>
<tbody>
    @foreach($client->tasks()->onlyTrashed()->get() as $task)                
<tr>
  <td>{{ $task->task }}</td> 
  <td>{{ $task->budget }}</td>  
  <td>{!! $task->performance !!}</td> 
  <td>{{ $task->duedate }}</td> 
  <td>{{ $task->author }}</td>
  <td>{{ $task->deleted_at }}</td> 
</tr>
    @endforeach
</tbody>
</table>
<strong><h3>Total earnings generated by {{$client->name}} per month: {{$sum}} USD</h3></strong><br>
@endif    
@endforeach
</x-layouts.porto>