<x-layouts.porto title="Notifications" 
header="Notifications" 
username={{$username}} 
profile_image={{$profile_image}} 
unread_notifications_number={{$unread_notifications_number}} 
:unread_notifications="$unread_notifications">
@foreach($users as $user)
<h2>Total earnings generated by {{$user->name}} per month: <strong>{{ $user->tasks()->onlyTrashed()->sum('budget'); }} USD</strong></h2>
@endforeach
</x-layouts.porto>