<x-layouts.porto title="Earnings by Users per Month" header="Earnings by Users per Month">
<h2>Total earnings generated by Andrey per month: <strong>{{ $earningsbyandrey }} USD</strong></h2>
<h2>Total earnings generated by Elena per month: <strong>{{ $earningsbyelena }} USD</strong></h2>
<br>
</x-layouts.porto>